Specifications: 
  Frequency: 86400  
  
Translation: 
  Performance Ratio: [Performance Ratio]
  Quality Control Index: [Quality Control Index]
  Availability: [Availability]
  RMSE DC Power: [RMSE DC Power]
  
Corrupt Values: [-999]

Range Bounds:
  Quality Control Index: [0,1]
  Performance Ratio: [0,1]
  Availability: [0,1]
  RMSE DC Power: [0,1]
  
Increment Bounds:
  Quality Control Index: [-0.5, None, False]
  Performance Ratio: [-0.5, None, False]
  Availability: [-0.5, None, False]
  RMSE DC Power: [-0.5, None, False]